package WL.Arrays.Exceptions is
   Bounds_Error : exception;

end WL.Arrays.Exceptions;
